name: Release

on:
  push:
    branches:
      - develop
      - master
    paths:
      - '.changeset/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Check Version
        id: check_version
        run: |
          json="{\"name\":\"@${{ github.repository }}\",\"private\":true,\"version\":\"{VERSION}\",\"devDependencies\":{\"@changesets/cli\":\"^2.27.1\"},\"packageManager\":\"pnpm@8.8.0\"}"
          initialVersion="0.0.0"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ ! -f ".version" ]; then
            touch .gitignore
            if ! grep -q "package.json" .gitignore; then
              echo "package.json" >> .gitignore
            fi
            echo "package.json" >> .gitignore
            echo "$initialVersion" > .version
            git add .version .gitignore
            git commit -m "chore: versioning setup"
            git push
          fi
          echo $json > package.json
          sed -i "s/{VERSION}/$(cat .version)/g" package.json
          echo "VERSION=$(cat .version)" >> $GITHUB_ENV
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Install Dependencies
        run: |
          pnpm install
      - uses: pnpm/action-setup@v4
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release"
          publish: "changeset tag && git push origin --tags"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
