name: Release

on:
  push:
    branches:
      - develop
      - master
    paths:
      - '.changeset/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Versioner Setup
        id: versioner
        run: |
          json="{\"name\":\"@${{ github.repository }}\",\"private\":true,\"version\":\"{VERSION}\",\"packageManager\":\"pnpm@8.8.0\"}"
          initialVersion="0.0.0"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global init.defaultBranch ${{ github.ref_name }}
          if [ ! -f ".version" ]; then
            touch .gitignore
            if ! grep -q "package.json" .gitignore; then
              echo "package.json" >> .gitignore
            fi
            echo "package.json" >> .gitignore
            echo "$initialVersion" > .version
            git add .version .gitignore
            git commit -m "chore: versioning setup"
            git push
          fi
          echo $json > package.json
          sed -i "s/{VERSION}/$(cat .version)/g" package.json
          echo "VERSION=$(cat .version)" >> $GITHUB_ENV
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
      - name: Install Dependencies
        run: |
          pnpm add @changesets/cli
      - name: Setup Node Path
        run: |
          echo "${{ github.workspace }}/node_modules/.bin" >> $GITHUB_PATH
      - uses: pnpm/action-setup@v4
      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Tag
        if: steps.changesets.outputs.pullRequestNumber
        run: |
          changeset tag
          git push origin --tags